[build]
directory = "/"
command = "npm install --prefix frontend && npm run build --prefix frontend"

[functions]
# Directory with serverless functions, including background
# functions, to deploy. This is relative to the base directory
# if one has been set, or the root directory if
# a base hasn’t been set.
directory = "./backend/netlify/"
